!classDefinition: #Pepe category: #'Ejercicio 2'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 2'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Ejercicio 2'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'accessing' stamp: 'Martin 4/5/2026 18:22:46'!
hola
	^'Hola Pepe'! !
