CC = gcc
CFLGAS = -Wall -Wextra  -g

SRCS = main.c \
			 utils.c \
			 verInfo.c \
			 agregarInfo.c \
			 buscarInfo.c 

TARGET = app

all:
	$(CC) $(SRCS) $(CFLGAS) -o $(TARGET)


clean:
	rm -f $(TARGET)


